import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextJS + TailwindCSS Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline">
        NextJS + TailwindCSS Starter
      </h1>
    </div>
  );
}
